{"name": "Появление ошибки при аутентификации с невалидными данными", "status": "passed", "parameters": [{"name": "incorrect_data", "value": "{'email': 'Skeptik', 'password': '123456'}"}], "start": 1745429646910, "stop": 1745429647003, "uuid": "9347ff8b-edfa-453a-ae11-66b3256570a0", "historyId": "9272e8afd6fdd688305596b08d7646e8", "testCaseId": "5e4c0b29060163f14563bb8e8caac3d8", "fullName": "test.test_login_user.TestUserLogin#test_login_incorrect__data", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-ROKST00"}, {"name": "thread", "value": "25868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_user"}]}