{"name": "Появление ошибки при аутентификации с невалидными данными", "status": "passed", "parameters": [{"name": "incorrect_data", "value": "{'email': 'gina45@mail.ru', 'password': '!*^V8Da#4s', 'name': 'Гаврила Харлампьевич Зиновьев'}"}], "start": 1745429646815, "stop": 1745429646908, "uuid": "e1b39b1b-e08d-4048-8ce5-8836a9f100d3", "historyId": "6651ecfdb3a7207c7285b0c3374f961c", "testCaseId": "5e4c0b29060163f14563bb8e8caac3d8", "fullName": "test.test_login_user.TestUserLogin#test_login_incorrect__data", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-ROKST00"}, {"name": "thread", "value": "25868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_user"}]}